spring:
  datasource:
    url: jdbc:h2:mem:notification-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tshortly
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.tshortly.events.url.ShortUrlAccessedEvent


app:
  kafka:
    topics:
      short-url-events: short-url-events
    consumer:
      group-id:
        notification: notification-service
        notification-dlt: notification-dlt-service
    retry:
      max-attempts: 3
      initial-intervals-ms: 2000
      multiplier: 2.0
      max-intervals-ms: 30000
    dlt:
      suffix: ".DLT"